---

services:
  backend:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
