<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TaskStatusTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
    }

    public function test_task_statuses_is_displayed(): void
    {
        $response = $this->get('/task_statuses');

        $response->assertOk();
    }

    public function test_task_status_create_form_is_displayed(): void
    {
        $response = $this
            ->actingAs($this->user)
            ->get('/task_statuses/create');

        $response->assertOk();
    }

    public function test_user_can_create_task_status(): void
    {
        $response = $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $response->assertRedirect('/task_statuses');

        $this->assertDatabaseHas('task_statuses', [
            'name' => 'in testing',
        ]);
    }

    public function test_user_cannot_duplicate_task_status(): void
    {
        $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $response = $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $response->assertRedirectBack();
    }

    public function test_task_status_edit_form_is_displayed(): void
    {
        $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $response = $this->get('/task_statuses/1/edit');

        $response->assertOk();
    }

    public function test_user_can_update_task_status(): void
    {
        $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $response = $this
            ->actingAs($this->user)
            ->patch('/task_statuses/1', [
                'name' => 'in reviewing',
            ]);

        $response->assertRedirect('/task_statuses');

        $this->assertDatabaseHas('task_statuses', [
            'name' => 'in reviewing',
        ]);

        $this->assertDatabaseMissing('task_statuses', [
            'name' => 'in testing',
        ]);
    }

    public function test_user_can_delete_task_status(): void
    {
        $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $this->assertDatabaseHas('task_statuses', [
            'name' => 'in testing',
        ]);

        $response = $this
            ->actingAs($this->user)
            ->delete('/task_statuses/1');

        $response->assertRedirect('/task_statuses');

        $this->assertDatabaseMissing('task_statuses', [
            'name' => 'in testing',
        ]);
    }

    public function test_user_cannot_delete_task_status_if_it_is_associated_with_task(): void
    {
        $this
            ->actingAs($this->user)
            ->post('/task_statuses', [
                'name' => 'in testing',
            ]);

        $this
            ->actingAs($this->user)
            ->post('/tasks', [
                'name' => 'Run tests',
                'description' => 'Some description',
                'status_id' => '1',
                'created_by_id' => $this->user->id,
                'assigned_to_id' => $this->user->id,
            ]);

        $this->assertDatabaseHas('task_statuses', [
            'name' => 'in testing',
        ]);

        $response = $this
            ->actingAs($this->user)
            ->delete('/task_statuses/1');

        $response->assertRedirect('/task_statuses');

        $this->assertDatabaseHas('task_statuses', [
            'name' => 'in testing',
        ]);
    }
}
